# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :dk do
	ipa_dir = "fastlane_build/"
	ipa_name = "打卡"+Time.new.strftime('%Y-%m-%d_%H:%M')
	archive_path = "./build/ipa/tem/archive/DailyClock.xcarchive"
	
	increment_build_number(xcodeproj:"DailyClock.xcodeproj")
	build_app(workspace:"DailyClock.xcworkspace",
	scheme:"DailyClock",
	configuration:"Debug",
	clean: true,
	output_directory:ipa_dir,
	archive_path:archive_path,
	export_options:{
	method:"development",
      	destination: "export",
      	stripSwiftSymbols: true,
      	teamID: "M99LZTCK8N",
      	uploadBitcode: false,
      	uploadSymbols: true,
      	provisioningProfiles: {"com.chengyan.DailyClock" => "DailyClockDev"}
	}
	)
  end

  desc "Test Flight"
  lane :dktf do
	username="ab364743113@qq.com"

	ENV["FASTLANE_USER"] = "ab364743113@qq.com"
	ENV["FASTLANE_PASSWORD"] = "Chengyan251"
	ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "svwk-xhcg-vccb-mbmb"

	ipa_dir = "fastlane_build/"
	ipa_name = "打卡"+Time.new.strftime('%Y-%m-%d_%H:%M')
	archive_path = "./build/ipa/tem/archive/DailyClock.xcarchive"
	
	increment_build_number(xcodeproj:"DailyClock.xcodeproj")
	build_app(workspace:"DailyClock.xcworkspace",
	scheme:"DailyClock",
	configuration:"Release",
	clean: true,
	output_directory:ipa_dir,
	archive_path:archive_path,
	export_options:{
	method:"app-store",
      	destination: "export",
      	stripSwiftSymbols: true,
      	teamID: "M99LZTCK8N",
      	uploadBitcode: false,
      	uploadSymbols: true,
      	provisioningProfiles: {"com.chengyan.DailyClock" => "DailyClockAppStore"}
	}
	)
	upload_to_testflight(
	ipa: ipa_dir+'/打卡.ipa',
	skip_waiting_for_build_processing: true
	)
  end

  desc "screet"
  lane:frame do
	snapshot
	frame_screenshots(white: true)
  end
end
