# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :dk do
	ipa_dir = "fastlane_build/"
	ipa_name = "打卡"+Time.new.strftime('%Y-%m-%d_%H:%M')
	archive_path = "./build/ipa/tem/archive/DailyClock.xcarchive"
	
	increment_build_number(xcodeproj:"DailyClock.xcodeproj")
	build_app(workspace:"DailyClock.xcworkspace",
	scheme:"DailyClock",
	configuration:"Debug",
	clean: true,
	output_directory:ipa_dir,
	archive_path:archive_path,
	export_options:{
	method:"development",
      	destination: "export",
      	stripSwiftSymbols: true,
      	teamID: "M99LZTCK8N",
      	uploadBitcode: false,
      	uploadSymbols: true,
      	provisioningProfiles: {"com.chengyan.DailyClock" => "DailyClockDev"}
	}
	)
  end

  desc "Test Flight"
  lane :dktf do
	username="ab364743113@qq.com"

	ENV["FASTLANE_USER"] = "ab364743113@qq.com"
	ENV["FASTLANE_PASSWORD"] = "Chengyan251"
	ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "svwk-xhcg-vccb-mbmb"

	ipa_dir = "fastlane_build/"
	ipa_name = "打卡"+Time.new.strftime('%Y-%m-%d_%H:%M')
	archive_path = "./build/ipa/tem/archive/DailyClock.xcarchive"
	
	increment_build_number(xcodeproj:"DailyClock.xcodeproj")
	build_app(workspace:"DailyClock.xcworkspace",
	scheme:"DailyClock",
	configuration:"Release",
	clean: true,
	output_directory:ipa_dir,
	archive_path:archive_path,
	export_options:{
	method:"app-store",
      	destination: "export",
      	stripSwiftSymbols: true,
      	teamID: "M99LZTCK8N",
      	uploadBitcode: false,
      	uploadSymbols: true,
      	provisioningProfiles: {"com.chengyan.DailyClock" => "DailyClockAppStore"}
	}
	)
	upload_to_testflight(
	ipa: ipa_dir+'/打卡.ipa',
	skip_waiting_for_build_processing: true
	)
  end

  desc "screet"
  lane:frame do
	#snapshot
	#frame_screenshots
	 frameit(
      white: true,
      # 使用iPhone 5s替代iPhone SE框架
      use_legacy_iphone5s: true,
      # 使用iPhone 6s替代iPhone 7框架
       use_legacy_iphone6s: true,
      # 使用iPhone X 替代iPhone XS框架
       use_legacy_iphonex: true,
      # 截图所在路径
      path: "./fastlane/screenshots"
    )

  end

 desc "app store"
	  lane:release do
	username="ab364743113@qq.com"

	ENV["FASTLANE_USER"] = "ab364743113@qq.com"
	ENV["FASTLANE_PASSWORD"] = "Chengyan251"
	ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "svwk-xhcg-vccb-mbmb"

	ipa_dir = "fastlane_build/"
	ipa_name = "打卡"+Time.new.strftime('%Y-%m-%d_%H:%M')
	archive_path = "./build/ipa/tem/archive/DailyClock.xcarchive"
	
	increment_build_number(xcodeproj:"DailyClock.xcodeproj")
	build_app(workspace:"DailyClock.xcworkspace",
	scheme:"DailyClock",
	configuration:"Release",
	clean: true,
	output_directory:ipa_dir,
	archive_path:archive_path,
	export_options:{
	method:"app-store",
      	destination: "export",
      	stripSwiftSymbols: true,
      	teamID: "M99LZTCK8N",
      	uploadBitcode: false,
      	uploadSymbols: true,
      	provisioningProfiles: {"com.chengyan.DailyClock" => "DailyClockAppStore"}
	}
	)
	upload_to_testflight(
	ipa: ipa_dir+'/打卡.ipa',
	skip_waiting_for_build_processing: true
	)
	
	#testflights
    #frame
	deliver_app

	end

	 desc "testflight"
	   lane:testflights do
	upload_to_testflight(
	ipa: ipa_dir+'/打卡.ipa',
	skip_waiting_for_build_processing: true
	)
		 end	
	
 desc "deliver_app"
	   lane:deliver_app do
		deliver(
  		submit_for_review: true,
  		force: true,
  		metadata_path: "./metadata",
		  skip_metadata: true,
skip_screenshots:true,

submission_information: {
add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
  }

	 	)
		 
		 end	
end
